version: "2.1"
services:
  web:
    image: hitalos/laravel:latest
    container_name: laravel
    ports:
        - 80:80
    volumes:
        - ./src/:/var/www/
    command: bash -c "php ./artisan serve --port=80 --host=0.0.0.0"